// Generated by station_7_video_compiler.py
export const scriptFiles: string[] = [
  "chuong_2.json",
  "compiled_019d861bbf3ea9d3bfcdd25458dcdbef.json",
  "compiled_019e1b29210e5da702bf5f591cdbb62e.json",
  "draft.json",
  "draft_ai.json",
  "reviewed_script.json",
  "reviewed_script_2.json"
];
export const actionFiles: string[] = [
  "combat_stance.json",
  "look_around.json",
  "reach_out.json",
  "sneak.json",
  "strike.json",
  "surprise_fear.json",
  "talk_angry.json",
  "talk_sad.json",
  "verified_run.json",
  "verified_walk.json"
];
export const characterFolders: string[] = [
  "char_001",
  "char_002",
  "char_minh",
  "char_mysterious_person",
  "char_tu_mong"
];
