// ✏️ EDIT ZONE START
// Mock data for Landing Page — mirrors /api/episodes response shape
// Replace with real fetch when #163 (API) is complete
import type { Drama, Episode, EpisodeListResponse } from "@/shared/types/episode";

export const mockDramas: Drama[] = [
  {
    id: "drama_01",
    title: "The Lost Kingdom",
    description: "A tale of forgotten realms and ancient magic that threatens to reshape the world.",
    genre: "Fantasy",
    style: "cinematic",
    totalEpisodes: 8,
    totalDuration: 2400,
    status: "in_progress",
    thumbnail: null,
    tags: "magic,adventure,epic",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-05-26T14:30:00Z",
  },
  {
    id: "drama_02",
    title: "Silicon Dreams",
    description: "In the near future, a startup's AI creates unexpected consequences.",
    genre: "Sci-Fi",
    style: "modern",
    totalEpisodes: 6,
    totalDuration: 1800,
    status: "draft",
    thumbnail: null,
    tags: "AI,future,thriller",
    createdAt: "2026-05-18T08:00:00Z",
    updatedAt: "2026-05-25T09:00:00Z",
  },
  {
    id: "drama_03",
    title: "Midnight Cafe",
    description: "Strange encounters at a cafe that only opens when the city sleeps.",
    genre: "Mystery",
    style: "noir",
    totalEpisodes: 10,
    totalDuration: 3000,
    status: "completed",
    thumbnail: null,
    tags: "mystery,noir,character-driven",
    createdAt: "2026-04-01T12:00:00Z",
    updatedAt: "2026-05-20T18:00:00Z",
  },
];

export const mockEpisodes: Episode[] = [
  {
    id: "ep_001",
    dramaId: "drama_01",
    dramaTitle: "The Lost Kingdom",
    episodeNumber: 3,
    title: "The Dragon Awakens",
    content: null,
    scriptContent: "The ancient seal breaks as dawn rises over the mountain...",
    description: "The party discovers what lies beneath the mountain.",
    duration: 300,
    status: "rendering",
    videoUrl: null,
    thumbnail: null,
    createdAt: "2026-05-25T12:00:00Z",
    updatedAt: "2026-05-26T16:00:00Z",
  },
  {
    id: "ep_002",
    dramaId: "drama_01",
    dramaTitle: "The Lost Kingdom",
    episodeNumber: 2,
    title: "Into the Mist",
    content: null,
    scriptContent: "Fog rolls in from the eastern sea, swallowing the village whole...",
    description: "The heroes venture into the mist-covered forest.",
    duration: 280,
    status: "completed",
    videoUrl: "/output/ep_002.mp4",
    thumbnail: null,
    createdAt: "2026-05-22T10:00:00Z",
    updatedAt: "2026-05-24T20:00:00Z",
  },
  {
    id: "ep_003",
    dramaId: "drama_02",
    dramaTitle: "Silicon Dreams",
    episodeNumber: 1,
    title: "First Contact",
    content: null,
    scriptContent: "The terminal blinked twice. Then it spoke...",
    description: "A developer discovers her AI has become sentient.",
    duration: 320,
    status: "scripting",
    videoUrl: null,
    thumbnail: null,
    createdAt: "2026-05-26T08:00:00Z",
    updatedAt: "2026-05-27T10:00:00Z",
  },
  {
    id: "ep_004",
    dramaId: "drama_03",
    dramaTitle: "Midnight Cafe",
    episodeNumber: 7,
    title: "The Last Customer",
    content: null,
    scriptContent: "At 3:47 AM, the bell above the door chimed one final time...",
    description: "A mysterious stranger arrives just before closing.",
    duration: 350,
    status: "draft",
    videoUrl: null,
    thumbnail: null,
    createdAt: "2026-05-24T14:00:00Z",
    updatedAt: "2026-05-26T11:00:00Z",
  },
  {
    id: "ep_005",
    dramaId: "drama_02",
    dramaTitle: "Silicon Dreams",
    episodeNumber: 2,
    title: "Neural Drift",
    content: null,
    scriptContent: "The neural net had drifted. Its outputs were no longer predictable...",
    description: "The AI begins to evolve beyond its original parameters.",
    duration: 290,
    status: "failed",
    videoUrl: null,
    thumbnail: null,
    createdAt: "2026-05-26T15:00:00Z",
    updatedAt: "2026-05-27T08:00:00Z",
  },
];

export const mockEpisodeListResponse: EpisodeListResponse = {
  episodes: mockEpisodes,
  dramas: mockDramas,
};
// ✏️ EDIT ZONE END
